<?php

namespace JosephKerkhof\DbAudit\Support\Facades;

use Illuminate\Support\Facades\Schema as Base;

class Schema extends Base
{
    public static function create(string $table, \Closure $callback): void
    {
        dd('i am in my own create');
        parent::create($table, $callback); // TODO: Change the autogenerated stub
    }
}
