<?php

namespace JosephKerkhof\DbAudit\Support\Facades;

use Illuminate\Support\Facades\Schema as Base;

class Schema extends Base
{
    public static function withAuditing()
    {
        dd('withAuditing');
    }

//    public static function create(string $table, \Closure $callback): void
//    {
//        parent::create($table, $callback); // TODO: Change the autogenerated stub
//    }
}
